import Head from "next/head";
import Experiences from "../components/experience/experiences";
import styles from "../styles/Home.module.css";

import {  useSelector } from "react-redux";
import {getSession} from 'next-auth/client'
import Login from "../components/auth/login";


export default function Home(props) {

  if(props['session'] == null){
    return <Login/>
  }

  const allPosts = useSelector(state => state.posts.posts)

  
  if(!allPosts){
    return <div> Loading.. </div>
  }
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Experience</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Experiences posts={allPosts}/>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const session = await getSession({ req: context.req });

    return {
      props: {
        session,
      },
    };
  
  
};
