import Head from "next/head";
import Experiences from "../components/experience/experiences";
import styles from "../styles/Home.module.css";

import {  useSelector } from "react-redux";


export default function Home() {

  const allPosts = useSelector(state => state.posts.posts)

  
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Experience</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Experiences posts={allPosts}/>
    </div>
  );
}

